### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by uniqueg** [biohackcloud/landing-page#7]
Create a contact form with the following fields (all required and validated):

- Full name
- Email address
- Subject
- Message

Upon submission, send an email formatted with the form fields to `support@biohack.cloud`.

In case you use SendGrid, I can provide you with an API key. If you need anything else, please let me know.

**Comment by neznayer** [comment]
@uniqueg  I think the simplest way is to use Google Forms for all notifications for now. 

In order to use SendGrid we will need a backend or a cloud function. Also we could use the Nextjs server for the Sendgrid, but then we will have to use vercel or netlify to deploy, because that would be not a static site anymore.

**Comment by uniqueg** [comment]
I think instead of keeping a "Contact" item in the nav bar and linking it to `mailto:support@biohack.cloud`, Instead we could link the "BioHackCloud 2023" in the footer to the email.
